Pages = [
	"http://www.future-x.de/drucker-laser-led-c-2_3848_5130_7829/?page=1",
	"http://www.future-x.de/drucker-laser-led-c-2_3848_5130_7829/?page=2",
	"http://www.future-x.de/drucker-laser-led-c-2_3848_5130_7829/?page=3",
	"http://www.future-x.de/drucker-laser-led-c-2_3848_5130_7829/?page=4"
]